### ISSUE TITLE
Group permissions

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#469]
Let's implement group permissions: if the user is a member of the group and repository operation is granted to this group, then this operation should also be allowed to the user. 

In the repo permissions, group names should start with `/`, is the example below `read` operation is granted for `readers` group
and every user within the group can read from the repository:
```yaml
repo:
  ...
  permissions:
    /readers:
      - read
```
