### ISSUE TITLE
Artipie permissions model

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#501]
As we discussed, let's work on the permissions model. For now, we agreed on the following points:
- permissions will extend `java.security.Permission` and use, if possible, various `java.security` features (like `AllPermission`)
- each adapter should have possibility to implement its own permissions version
- users' permissions will be parsed/read from somewhere by `Policy` interface (or group of interfaces) and it should be possible to add custom `Policy` implementation by providing corresponding `jar` and some specific configuration 
-  users' permissions should be cached
- from the box we will first of all support yaml permissions and yaml policy. The format if the following: in the configuration storage each user will have his own yaml config with credentials, some info and roles:
```
security
├── roles
│   ├── java-dev.yaml
│   ├── admin.yml
│   ├── ...
├── users
│   ├── david.yaml
│   ├── jane.yaml
│   ├── ...
```
where `roles` contain an existing roles files (one file for one role) in the following format:
```yaml
# java-dev.yaml
java-dev: # role name
  artipie_basic_permission: # the name of the `java.security.Permission` implementation
    maven-repo: # repository name
      - read
      - write
    python-repo:
      - read
    npm-repo:
      - read
```
```yaml
# admin.yaml
admin:
  artipie_all_permission: {} # the name of the `java.security.Permission` implementation
```

User's yaml setting class has the following format:
```yaml
david:
  type: plain
  pass: qwerty
  email: jane@example.com # Optional
  enabled: true # optional default true
  roles:
    - java-dev
  permissions:
    artipie_basic_permission:
      rpm-repo:
        - read
```
